baseURL = "https://datatrustmanifesto.org/"
languageCode = "en-us"
title = "Data Trust Engineering | EMM 2.0"

[params]
description = "Data Trust Engineering (DTE): Certify data systems for trust and AI-readiness. Join the #DataTrustCommunity!"
keywords = "data trust engineering, AI governance, DataOps, data certification"
site_domain = "datatrustmanifesto.org"

# Custom mounts to preserve existing file structure (Serving in Hugo Site which renders the .md as pages)
[[module.mounts]]
  source = "."
  target = "content"
  includeFiles = ["Manifesto.md"]
[[module.mounts]]
  source = "tools"
  target = "content/tools"
  includeFiles = ["data-trust-dashboard/DTE_Trust_Dashboard.html", "lineage-tracker/lineage-script.py"]
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "Manifesto"
  url = "/Manifesto"
  weight = 2

[[menu.main]]
  name = "Trust Dashboard"
  url = "/tools/data-trust-dashboard/DTE_Trust_Dashboard"
  weight = 3
[[menu.main]]
  name = "Github"
  url = "https://github.com/datatrustengineering/DataTrustEngineering"
  weight = 4
[[menu.main]]
  name = "Slack"
  url = "https://join.slack.com/t/datatrustengineering/shared_invite/zt-3br05le6v-pxGSBeJGLpVgOsNM9ejGuw"
  weight = 5

# Add EMM2.0.md to mounts
[[module.mounts]]
  source = "docs/frameworks"
  target = "content/docs/frameworks"
  includeFiles = ["EMM20.md"]

# Fix the menu URL
[[menu.main]]
  name = "Frameworks"
  url = "/docs/frameworks/emm20/"
  weight = 3

# Disable Hugo's automatic sitemap generation
[outputs]
  home = ["HTML"]
  page = ["HTML"]  
  section = ["HTML"]


# Disable RSS feeds and other auto-generated content
disableKinds = ["RSS", "taxonomy", "term", "robotsTXT", "404"]

[sitemap]
  disable = true
